### PR TITLE
optimisation

### PR DESCRIPTION
**Pull request by cptsanifair**
fixed some CSS lines
short some php if-else cases to switch or shorter

### CODE REVIEW

**Comment by cptsanifair** [comment]
to much files ;)

**Comment by cptsanifair** [comment]
i cant contribute without adding my nbproject folder... :S

**Review by aljawaid — APPROVED** [review]
Hello, thanks for this.  I noticed you have used php v8.x... have you tested your changes? Will it all work with php7.x also?

**Review by aljawaid — COMMENTED** [review]
You have pushed a .yaml file for the compatibility. Do I just merge it? I am not familiar with workflows and dont know how to set them up so I dont know what this file will do when I merge it.

**Comment by cptsanifair** [comment]
there is more incomming ;)

the yaml file was not planed to add to your repository

**Comment by cptsanifair** [comment]
ok, i think i'm done.

Maybe later more, but in a new request if needed.

for your understanding:
- actions will run on push, and verify the compatibility to the specifics PHP Version
- the "code cleanup" 
  - replaces if-else through switches
  - adapt to en_GB\translations.php and translations-starter-template.php
- add .gitignore

**Comment by aljawaid** [comment]
Thanks for your efforts and also for the explanation

**Pull request merged**
