### PR TITLE
Install plugins by file or URL

### PR DESCRIPTION
**Pull request by alfredbuehler**
This is some work in progress. I have added this on top of the manual plugin page. 
Please don't hesitate to move it elsewhere, but I think, manual plugins is a good place.
Of course, there is some styling required, what is fully up to you.

### CODE REVIEW

**Review by aljawaid — APPROVED** [review]

**Comment by aljawaid** [comment]
wow what a nice surprise.... thanks a lot, I will add you to the repo so you dont have to do pr

**Comment by alfredbuehler** [comment]
> have you got something left to do on it or is it just the styling

No, just location & styling.

**Comment by aljawaid** [comment]
> > have you got something left to do on it or is it just the styling
> 
> No, just location & styling.

ok I will do the styling, let me know when you are done with the location part... i added you to repo

**Comment by alfredbuehler** [comment]
No, I'm done with this. Move it if you like.

**Pull request merged**
